module.exports = [
  { id: 1, ingredient: 'broccoli', image: 'broccoli.png' },
  { id: 2, ingredient: 'red onion', image: 'red_onion.png' },
  { id: 3, ingredient: 'cheese', image: '  swiss_cheese.png' },
  { id: 4, ingredient: 'carrots', image: 'carrots.png' },
  { id: 5, ingredient: 'milk', image: 'milk.png' },
  { id: 6, ingredient: 'butter', image: 'butter.png' },
  { id: 7, ingredient: 'grapes', image: 'grapes.png' },
  { id: 8, ingredient: 'potatoes', image: 'potatoes.png' },
  { id: 9, ingredient: 'salsa', image: 'salsa.png' },
  { id: 10, ingredient: 'chicken', image: 'chicken.png' },
  { id: 11, ingredient: 'steak', image: 'steak.png' },
  { id: 12, ingredient: 'salmon', image: 'salmon.png' },
  { id: 13, ingredient: 'eggs', image: 'eggs.png' },
  { id: 14, ingredient: 'rice', image: 'rice.png' },
  { id: 15, ingredient: 'shrimp', image: 'shrimp.png' },
  { id: 16, ingredient: 'lobster', image: 'lobster.png' },
  { id: 17, ingredient: 'beer', image: 'beer.png' },
  { id: 18, ingredient: 'soda', image: 'soda.png' },
  { id: 19, ingredient: 'turkey', image: 'turkey.png' },
  { id: 20, ingredient: 'pasta', image: 'pasta.png' },
  { id: 21, ingredient: 'tomatoes', image: 'tomatoes.png' },
  { id: 22, ingredient: 'BBQ sauce', image: 'bbq-sauce.png' },
  { id: 24, ingredient: 'ham', image: 'ham.png' },
  { id: 25, ingredient: 'vanilla', image: 'vanilla.png' },
  { id: 26, ingredient: 'bacon', image: 'bacon.png' },
  { id: 27, ingredient: 'meatballs', image: 'meatballs.png' },
  { id: 28, ingredient: 'peppers', image: 'peppers.png' },
  { id: 29, ingredient: 'mushrooms', image: 'mushrooms.png' },
  { id: 30, ingredient: 'garlic', image: 'garlic.png' },
  { id: 31, ingredient: 'hot dogs', image: 'hot-dogs.png' },
];
